# Generated by Django 5.2.5 on 2025-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_buyer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cents',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='order',
            name='total_pesos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_pesos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='MXN', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='MXN', max_length=10),
        ),
    ]
